### ISSUE TITLE
How to close the Incident & Task using Rest API through Python

### ISSUE THREAD

**Issue by krlplm** [ibmresilient/resilient-python-examples#1]
Hi,

Is there a way to close the Incident & Task accessing Rest API through Python?

Thanks,
Hem

**Comment by yassipo** [comment]
Hi,

I use this update method:

`    def update_status(task):
        task["status"] = "C"
`

and then close via api:

`
conn.get_put("/tasks/{}"),lambda task: update_status(task))
                                     
`

**Comment by krlplm** [comment]
Thanks. The suggestion worked by setting the corresponding field as C.
