### ISSUE TITLE
Query example with several conditions

### ISSUE THREAD

**Issue by j4zzcat** [ibmresilient/resilient-python-examples#3]
What's the syntax for specifying several conditions in a gadget json query? i.e., `field1 = "foo" and field2 = "bar"`.

**Comment by hpyle** [comment]
Great question.  You can just include multiple conditions in the array; the result will be incidents that match all the conditions supplied.  (For rule conditions there's a more flexible syntax that allows "AND" and "OR" and custom combinations, but you can't currently use that with the Query API).

For example, here's a query that includes conditions for two fields,
```
{
  "filters": [
    {
      "conditions": [
        {
          "field_name": "name",
          "method": "contains",
          "value": "test"
        },
        {
          "field_name": "incident.properties.mytestfield",
          "method": "equals",
          "value": "abc"
        }
      ]
    }
  ]
}
```

**Comment by j4zzcat** [comment]
Thanks. Wouldn't it be better to add it to the examples?
