### ISSUE TITLE
Put Conflicts while updating ticket from Splunk Phantom

### ISSUE THREAD

**Issue by nirajKpanda** [ibmresilient/resilient-python-examples#6]
Hi Resilient Dev Team,

I am using Resilient app integrated with my Splunk Phantom app to create and update Resilient tickets. While updating I am getting Put conflicts.

I have used following json to update ticket api from Phantom asset.

{
  "name" : "Default name",
  "description" : "Default description",
  "discovered_date": 0,
  "regulators" : {
    "ids" : [
      149
    ]
  },
  "crimestatus_id": 5,
  "exposure_type_id": 1
}

Please help me if I am wrong or help me getting the correct json structure to update the ticket.

**Comment by allenhadden** [comment]
There are two ways you can update a case/ticket.  First, you can do a GET followed by a PUT.  The Resilient Python API has a get_put method that simplifies this and also handles any edit conflicts by doing a retry.  Here's an example (taken from an example in this repo):

```
        def _update_inc(incident):
            """Function to add an incident type to an incident"""
            LOG.info('Updated incident with %s type', new_inc_type)
            incident['incident_type_ids'].append(new_inc_type)
            return incident

        # Updates the incident with the new incident type
        self.rest_client().get_put('/incidents/{}'.format(inc_id),
                                   _update_inc, co3_context_token=event.context)
```

The other way to do it is to use the Resilient REST API's PATCH support.  There are examples here:

https://github.com/ibmresilient/resilient-python-examples/tree/0cf30f6edfb7c7077f53ff06a9d73929e391713a/patch-incident

Hope that helps.  I've closed this issue...if you're still having problems then feel free to reopen.

**Comment by nirajKpanda** [comment]
I am almost doing the same from Phantom.

1. Getting the existing ticket id which needs to be updated.
2. Applying json body data to update the ticket field.

Result - Put Conflicts

Any reason why getting Put conflicts, is this related to any permission/data integrity or other issue?

**Comment by allenhadden** [comment]
I'm not sure what's going on in Phantom.  I assume you're not talking about a busy system with other users editing that incident (i.e. that we're not talking about an _actual_ conflict).

A PUT conflict usually means that the "version" field on the object you're sending is different than what is expected by the server (i.e. it's different than the value stored in the DB).

I have a suspicion that whatever Phantom operations you're using to do the PUT is overwriting some or all of the value from the GET.  The Resilient server's log file (/usr/share/co3/lobs/client.log) might contain useful information.
